# `Stages` are the order that the pipeline is executing the jobs. The each stage are executed sequentially.
stages:
  # `build` is the stage
  build:
    # each item in this list is a job.
    - image
    - chart
  tag:
    - cleanup
    - tag
  predeploy:
    - namespace
    - cloudflare-credentials
    - cloudflare-issuer
  dev:
    - dry-run
    - deploy

# `Variables` are the environment variables that are used in the pipeline. The variables are available to all jobs. The variables can be overridden in the job level.
# Default Variables are available on top of these key/value.
variables:
  # `VERSION` is the name of the global variable
  - name: VERSION
    # `options` are the options that the variable can be selected.
    value: "$COMMIT_ID"
    # `description` is the description of the variable. This will be displayed in the deploy page.
    description: "Select your version."
  - name: GIT_CREDENTIAL
    value: "github"
    description: "Credential to use for git related actions."
  - name: TARGET
    default: "dev"
    options:
      - "dev"
      - "test"
      - "prod"
    description: "Which cluster to deploy to."
  - name: BUILD
    default: "false"
    options:
      - "true"
      - "false"
  - name: TAG
    default: "false"
    options:
      - "true"
      - "false"
    description: "If application should be tagged."
  - name: DEPLOY
    default: "false"
    options:
      - "true"
      - "false"
    description: "If application and dependencies should be deployed."
  - name: NAMESPACE
    default: "test"
    options:
      - "test"
      - "dev"
    description: "Namespace to deploy in."
  - name: SERVICE_URL
    default: "myapp.myorg.ankra.app"
    options:
      - "myapp.myorg.ankra.app"
      - "myapp.dev.myorg.ankra.app"
    description: "Service URL to deploy in."

# `build` is the name of the stage.
build:
  # `conditions` state the conditions that must be met to execute stage.
  conditions:
    # When handles general condition handling in UNIX format.
    - when: "$BUILD"
  # `target` is the cluster the stage is executed on.
  target:
    # `match` clusters on the parameters provided.
    match:
      # `name` is the name of the target
      name: $TARGET
  # `image` is the a job in this stage.
  image:
    # `docker` is the docker module.
    docker:
    # `actions` are the actions that the docker module will execute.
      actions:
        - action: build
          name: $PROJECT_NAME/$APPLICATION_NAME
          tag: $VERSION
  chart:
    # `helm` is the helm module.
    helm:
      # `actions` are the actions that the helm module will execute.
      actions:
        - action: package
          path: $WORKSPACE/helm
          push: true

# `tag` is the name of the stage.
tag:
  # `conditions` state the conditions that must be met to execute stage.
  conditions:
    - when: "$TAG"
  # `target` is the cluster the stage is executed on.
  target:
    match:
      name: $TARGET
  # `cleanup` is the a job in this stage. This job is executed to clean up any tag conflicts.
  cleanup:
    # `allow_failure` is the flag that the job is allowed to fail.
    allow_failure: true
    # `git` is the git module.
    git:
      # Keys defined at this level are global keys available to all actions.
      provider: $GIT_PROVIDER
      credential: $GIT_CREDENTIAL
      tag: $VERSION
      # `actions` are the actions that the git module is executed.
      actions:
        - action: delete_tag
        - action: push_tag
  # `tag` is the a job in this stage. This job is executed to create a tag.
  tag:
    git:
      # Keys defined at this level are global keys available to all actions.
      provider: $GIT_PROVIDER
      credential: $GIT_CREDENTIAL
      tag: $VERSION
      actions:
        - action: tag
          message: "$APPLICATION_NAME $VERSION"
        - action: push_tag

# `predeploy` is the name of the stage.
predeploy:
  # `conditions` are the conditions that the stage is executed.
  conditions:
    - when: "$DEPLOY"
  # `target` is the target that the stage is executed.
  target:
    match:
      name: $TARGET
  # `namespace` is the a job in this stage. This job is executed to create a namespace.
  namespace:
    # `script` is the script module.
    script:
      # `commands` are the commands that the script module is executed.
      commands:
      - if [[ ! $(kubectl get ns $NAMESPACE) ]]; then
          kubectl create ns $NAMESPACE;
        fi
  # `cloudflare-credentials` is the a job in this stage. This job is executed to create a secret for cloudflare.
  cloudflare-credentials:
    # `secrets` are the secrets available to this job.
    secrets:
      - ORIGIN_KEY
    script:
      commands:
        - if [[ ! $(kubectl get secret service-key -n $NAMESPACE) ]]; then
            kubectl -n $NAMESPACE create secret generic service-key --from-literal key=${ORIGIN_KEY};
          fi
  # `cloudflare-issuer` is the a job in this stage. This job is executed to create a cloudflare issuer.
  cloudflare-issuer:
    # `secrets` are the secrets available to this job.
    secrets:
      - ORIGIN_KEY
    script:
      commands:
        - kubectl -n $NAMESPACE apply -f https://artifact.infra.ankra.cloud/repository/ankra-install-public/manifests/origin-issuer.yaml

# `dev` is the stage.
dev:
  # `conditions` are the conditions that the stage is executed.
  conditions:
    - when: "$DEPLOY"
  # `target` is the target that the stage is executed.
  target:
    match:
      name: $TARGET
  # `dry-run` is the a job in this stage. This job is executed to deploy the helm chart in dry-run mode.
  dry-run:
    helm:
      actions:
        # `add_repository` is the action that adds a helm repository. This is used to add additional depedencies for the general flow.
        - action: add_repository
          name: common
          url: https://charts.bitnami.com/bitnami
        - action: upgrade
          build_dependencies: true
          name: $APPLICATION_NAME
          namespace: $NAMESPACE
          chart: $WORKSPACE/helm
          dry_run: true
          extra_args:
            - --set image.tag=$VERSION
  # `deploy` is the a job in this stage. This job is executed to deploy the helm chart.
  deploy:
    helm:
      actions:
        - action: add_repository
          name: common
          url: https://charts.bitnami.com/bitnami
        - action: upgrade
          name: $APPLICATION_NAME
          namespace: $NAMESPACE
          chart: $WORKSPACE/helm
          build_dependencies: true
          extra_args:
            - --set image.tag=$VERSION
            - --set fullnameOverride=$APPLICATION_NAME
            - --set global.environment=prod
            - --set ingress.hostname="$SERVICE_URL"
            - --set ingress.external_dns.target="lb-$CLUSTER_ID.ankra.dev"
            - --set commonLabels='ankra.app/external-dns: \"true\"'
