{{- $environment := .Values.global.environment -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "aws.fullname" . }}-worker
  labels:
    aws.type: "worker"
    {{- include "aws.labels" . | nindent 4 }}
spec:
{{- if not .Values.worker.autoscaling.enabled }}
  replicas: {{ .Values.worker.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      aws.type: "worker"
  template:
    metadata:
    {{- with .Values.worker.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        aws.type: "worker"
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "worker.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.worker.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-worker
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          {{- if eq $environment "prod" }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          {{- else }}
          image: "{{ .Values.image.repository }}:{{ .Release.Namespace }}-latest"
          {{ end }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if eq $environment "local" }}
          volumeMounts:
            - name: src-volume
              mountPath: /opt/src
          {{- end }}
          env:
          - name: APPLICATION_NAME
            value: worker
          - name: ENV
            value: {{ $environment }}
          - name: NAMESPACE
            value: {{ .Release.Namespace }}
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: SERVICE_ACCOUNT
            value: {{ include "worker.serviceAccountName" . }}
          resources:
            {{- toYaml .Values.worker.resources | nindent 12 }}
      {{- if eq $environment "local" }}
      volumes:
        - name: src-volume
          hostPath:
            path: /workdir/platform/aws/src
            type: Directory
      {{- end }}
